<?php

#-- WIKI START
$WT = array();
$WTTOP = array();
$WTMID = array();
$WTBOT = array();
/* $ServerName comes from interface_design_templater.php */
if ($terminology == "HTML-O") {
	array_push($WTTOP,"HTML Obfuscation-----//$ServerName/wikipedia.htm?st=Obfuscation_(software)-----Obfuscated code is source or machine code that has been made difficult to understand. Programmers may deliberately obfuscate code to conceal its purpose or its logic to prevent tampering, deter reverse engineering or as a puzzle or recreational challenge for readers. It is a form of security through obscurity. Programs known as obfuscators transform readable code into obfuscated code using various techniques that might induce anti-debugging, anti-decompilation and anti-disassembly mechanism.");
	array_push($WTTOP,"Data Cryptography-----//$ServerName/wikipedia.htm?st=Cryptography-----Cryptography is the practice and study of hiding information. Modern cryptography intersects the disciplines of mathematics, computer science, and engineering. Applications of cryptography include ATM cards, computer passwords, and electronic commerce.");

	array_push($WTMID,"Cryptanalysis-----//$ServerName/wikipedia.htm?st=Cryptanalysis-----Cryptanalysis is the study of methods for obtaining the meaning of encrypted information, without access to the secret information that is normally required to do so. Typically, this involves knowing how the system works and finding a secret key. In non-technical language, this is the practice of codebreaking or cracking the code, although these phrases also have a specialized technical meaning.");
	array_push($WTMID,"Data Encryption-----//$ServerName/wikipedia.htm?st=Cryptography-----Until modern times cryptography referred almost exclusively to data encryption, which is the process of converting ordinary information (plaintext) into unintelligible gibberish (i.e., ciphertext). Decryption is the reverse, in other words, moving from the unintelligible ciphertext back to plaintext. A cipher (or cypher) is a pair of algorithms that create the data encryption and the reversing decryption. The detailed operation of a cipher is controlled both by the algorithm and in each instance by a key. This is a secret parameter (ideally known only to the communicants) for a specific message exchange context.");
	array_push($WTMID,"Obfuscation-----//$ServerName/wikipedia.htm?st=Obfuscation-----Obfuscation is the concealment of intended meaning in communication, making communication confusing, intentionally ambiguous, and more difficult to interpret. Obfuscation may be used for many purposes. Doctors have been accused of using jargon to conceal unpleasant facts from a patient; American author Michael Crichton claimed that medical writing is a &lsquo;highly skilled, calculated attempt to confuse the reader&rsquo;. B. F. Skinner, noted psychologist, commented on medical notation as a form of multiple audience control, which allows the doctor to communicate to the pharmacist things which might be opposed by the patient if they could understand it.");
	array_push($WTMID,"E-mail Privacy-----//$ServerName/wikipedia.htm?st=Email_privacy-----The protection of electronic mail from unauthorized access and inspection is known as electronic privacy. In countries with a constitutional guarantee of the secrecy of correspondence, e-mail is equated with letters and thus legally protected from all forms of eavesdropping. %%BR%%  %%BR%% In the United States, privacy of correspondence is derived from the Fourth Amendment to the United States Constitution and thus restricted by the requirement for a &quot;reasonable expectation of privacy&quot;.");
	array_push($WTMID,"Data Masking-----//$ServerName/wikipedia.htm?st=Data masking-----Data masking is the process of obscuring (masking) specific data elements within data stores. It ensures that sensitive data is replaced with realistic but not real data. The goal is that sensitive customer information is not available outside of the authorized environment. Data masking is typically done while provisioning non-production environments so that copies created to support test and development processes are not exposing sensitive information and thus avoiding risks of leaking. Masking algorithms are designed to be repeatable so referential integrity is maintained.");
	array_push($WTMID,"HTTP Secure-----//$ServerName/wikipedia.htm?st=HTTP Secure-----Hypertext Transfer Protocol Secure (HTTPS) is a combination of the Hypertext Transfer Protocol with the SSL/TLS protocol to provide encryption and secure (website security testing) identification of the server. It uses port 443. HTTPS connections are often used for payment transactions on the World Wide Web and for sensitive transactions in corporate information systems. HTTPS should not be confused with Secure HTTP (S-HTTP) specified in &quot;RFC 2660&quot;.");

	array_push($WTBOT,"Data Encryption Standard-----//$ServerName/wikipedia.htm?st=Data Encryption Standard-----The Data Encryption Standard (DES) is a block cipher (a form of shared secret encryption) that was selected by the National Bureau of Standards as an official Federal Information Processing Standard (FIPS) for the United States in 1976 and which has subsequently enjoyed widespread use internationally. It is based on a symmetric-key algorithm that uses a 56-bit key. The algorithm was initially controversial with classified design elements, a relatively short key length, and suspicions about a National Security Agency (NSA) backdoor.");
	array_push($WTBOT,"Advanced Encryption Standard-----//$ServerName/wikipedia.htm?st=Advanced Encryption Standard-----In cryptography, the Advanced Encryption Standard (AES) is a symmetric-key encryption standard adopted by the U.S. government. The standard comprises three block ciphers, AES-128, AES-192 and AES-256, adopted from a larger collection originally published as Rijndael. Each of these ciphers has a 128-bit block size, with key sizes of 128, 192 and 256 bits, respectively. The AES ciphers have been analyzed extensively and are now used worldwide, as was the case with its predecessor, the Data Encryption Standard (DES).");
	array_push($WTBOT,"Security Through Obscurity-----//$ServerName/wikipedia.htm?st=Security through obscurity-----Security through (or by) obscurity is a pejorative referring to a principle in security engineering, which attempts to use secrecy (of design, implementation, etc.) to provide security. A system relying on security through obscurity may have theoretical or actual security vulnerabilities, but its owners or designers believe that the flaws are not known, and that attackers are unlikely to find them.");
}
else if ($terminology == "ECOM") {
	array_push($WTTOP,"Transactional Link-----//$ServerName/wikipedia.htm?st=Transactional_Link-----A transactional link is a type of hyperlink link used in ecommerce to initiate a purchase. While a hyperlink can be used to send a user anywhere on the internet, a transactional link is specifically designed to direct the user to complete a sale. On a website selling products, this is typically a link to add items to the shopping cart or to checkout. Online transaction processing, or OLTP, refers to a class of systems that facilitate and manage transaction-oriented applications, typically for data entry and retrieval transaction processing.&lt;br&gt;&lt;br&gt;Buttons, generated by the &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin, are considered &lsquo;Transactional Links&rsquo;, or in other words, links which if clicked will lead directly to a payment processing system to attempt the completion of a quick sale.");
	array_push($WTTOP,"Mobile Commerce-----//$ServerName/wikipedia.htm?st=Mobile_commerce-----Mobile commerce services were first delivered in 1997, when the first two mobile-phone enabled Coca Cola vending machines were installed in the Helsinki area in Finland. The machines accepted payment via SMS text messages. The first mobile phone-based banking service was launched in 1997 by Merita Bank of Finland, also using SMS.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin gives you all the tools to quick and easily setup an online store to start selling your products, services, digital content or anything else you want to sell to any device connected to the internet, including mobile devices.");
	array_push($WTTOP,"Payment System-----//$ServerName/wikipedia.htm?st=Payment_system-----A payment system is a system used for transferring money. With the advent of computers and electronic communications a large number of alternative electronic payment systems have emerged. These include debit cards, credit cards, electronic funds transfers, direct credits, direct debits, internet banking and e-commerce payment systems. Payment systems are used in lieu of tendering cash in domestic and international transactions.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin utilizes online payment processing services by both PayPal and Google Wallet (formerly Google Checkout), both highly trusted institutions with a strong financial backing.");
	array_push($WTTOP,"HTML Obfuscation-----//$ServerName/wikipedia.htm?st=Obfuscation_(software)-----Obfuscated code is source or machine code that has been made difficult to understand. Programmers may deliberately obfuscate code to conceal its purpose or its logic to prevent tampering, deter reverse engineering or as a puzzle or recreational challenge for readers. It is a form of security through obscurity. Programs known as obfuscators transform readable code into obfuscated code using various techniques that might induce anti-debugging, anti-decompilation and anti-disassembly mechanism.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin, by VPS-NET, gives you the option of obfuscating HTML for your &lsquo;BuyItNow&rsquo; buttons on-the-fly.");

	array_push($WTMID,"Shopping Cart-----//$ServerName/wikipedia.htm?st=Shopping_cart_software-----In online marketing, a shopping cart is a piece of e-commerce software on a web server that allows visitors to an internet site to select items for eventual purchase, analogous to the term &lsquo;shopping cart&rsquo; or &lsquo;shopping basket.&rsquo;&lt;br&gt;&lt;br&gt;To a degree, the &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin can be considered shopping cart software, since it dynamically generates a sales platform from which to sell products online.");
	array_push($WTMID,"Credit Card-----//$ServerName/wikipedia.htm?st=Credit_card-----A credit card is a payment card issued to users as a system of payment. It allows the cardholder to pay for goods and services based on the holder's promise to pay for them.[1] The issuer of the card creates a revolving account and grants a line of credit to the consumer (or the user) from which the user can borrow money for payment to a merchant or as a cash advance to the user.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin utilizes online transaction processing systems by both PayPal and Google Wallet (formerly Google Checkout) to process credit card payments, as well as verify end-user identities.");
	array_push($WTMID,"Obfuscation-----//$ServerName/wikipedia.htm?st=Obfuscation-----Obfuscation is the concealment of intended meaning in communication, making communication confusing, intentionally ambiguous, and more difficult to interpret. Obfuscation may be used for many purposes.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin gives you the option of obfuscating your BuyItNow buttons on-the-fly.");
	array_push($WTMID,"HTTP Secure-----//$ServerName/wikipedia.htm?st=HTTP Secure-----Hypertext Transfer Protocol Secure (HTTPS) is a combination of the Hypertext Transfer Protocol with the SSL/TLS protocol to provide encryption and secure (website security testing) identification of the server. It uses port 443. HTTPS connections are often used for payment transactions on the World Wide Web and for sensitive transactions in corporate information systems.&lt;br&gt;&lt;br&gt;By using the &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin, you don't necessarily need to use HTTPS to secure your web server and online store. Considering the fact BuyItNow Advanced uses secure payment processing services provided by PayPal and Google, the need for HTTPS isn't quite necessary to maintain a secure online store.");
	array_push($WTMID,"Data Masking-----//$ServerName/wikipedia.htm?st=Data masking-----Data masking is the process of obscuring (masking) specific data elements within data stores. It ensures that sensitive data is replaced with realistic but not real data. The goal is that sensitive customer information is not available outside of the authorized environment. Data masking is typically done while provisioning non-production environments so that copies created to support test and development processes are not exposing sensitive information and thus avoiding risks of leaking. Masking algorithms are designed to be repeatable so referential integrity is maintained.&lt;br&gt;&lt;br&gt;The processes encompassing the &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin, which utilize various methods and techniques of masking data, allow for a safe and secure virtual platform from which to interactively sell your producs online.");

	array_push($WTBOT,"E-Commerce Payment System-----//$ServerName/wikipedia.htm?st=E-commerce_payment_system-----An e-commerce payment system facilitates the acceptance of electronic payment for online transactions. Also known as a sample of Electronic Data Interchange (EDI), e-commerce payment systems have become increasingly popular due to the widespread use of the internet-based shopping and banking. Over the years, credit cards have become one of the most common forms of payment for e-commerce transactions. In North America almost 90% of online B2C transactions were made with this payment type.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin utilizes online payment processing services by both PayPal and Google Wallet (formerly Google Checkout), both highly trusted institutions with a strong financial backing.");
	array_push($WTBOT,"Online Transaction Processing-----//$ServerName/wikipedia.htm?st=Online_transaction_processing-----Online transaction processing, or OLTP, refers to a class of systems that facilitate and manage transaction-oriented applications, typically for data entry and retrieval transaction processing. The term is somewhat ambiguous; some understand a &lsquo;transaction&rsquo; in the context of computer or database transactions, while others (such as the Transaction Processing Performance Council) define it in terms of business or commercial transactions.&lt;br&gt;&lt;br&gt;The &lsquo;BuyItNow Advanced&rsquo; Wordpress plugin utilizes online transaction processing systems by both PayPal and Google Wallet (formerly Google Checkout) to process payments, as well as verify end-user identities.");
}


$countWiki = 0;
shuffle($WTBOT);shuffle($WTMID);shuffle($WTTOP);
// force a count of 10, considering we want the 3 bot ones to always show, we need to remove one from middle
if ($terminology == "HTML-O") {
	$wackonemiddleman = array_pop($WTMID);
}
else if ($terminology == "ECOM") {
	$wackonetopman = array_pop($WTTOP);
	$wacktwotopman = array_pop($WTTOP);

	$wacktwomidman = array_pop($WTMID);
	$wacktwomidman = array_pop($WTMID);
	$wacktwomidman = array_pop($WTMID);

	$wacktwobotman = array_pop($WTBOT);
}


$losDefaultWIKI = "<style type=\"text-css\">.Wiki-Peeks-Wikipedia-Javascript-jQuery{width:1px;height:1px;clip:rect(0px,1px,1px,0px);overflow:hidden;}</style>";
$WT = array_merge((array)$WTTOP, (array)$WTMID, (array)$WTBOT);
foreach ($WT as $WTi) {
	$esteWiki= explode("-----", $WTi);
	$T = $esteWiki[0];$L = $esteWiki[1];$D = $esteWiki[2];
	$bS = ""; $bE = ""; 
	##-- loadparse 10
	if ($countWiki < 10) {
		if ($countWiki === 0) { $bS = "<b>"; $bE = "</b>"; $fSize = ''; }
		else { $bS = "<sup>.</sup> &nbsp;"; $bE = ""; $fSize = 'font-size:11px;'; }
		$losDefaultWIKI = $losDefaultWIKI . "<div class=\"panelBarWIKIitem\">" . $bS . "<a href=\"$L\" class=\"WikiBoard\" style=\"color:#666666;" . $fSize ."\" target=\"WIKI\" onmouseover=\"this.style.color='#CC0000';\" onmouseout=\"this.style.color='#666666';\" title=\"$T %%%%% $D\"><span title=\"WikiPeeks: ".$T." [Source: Wikipedia]\" class=\"Wiki-Peeks-Wikipedia-Javascript-jQuery\"><img src=\"/web_design_imagery/spacer.gif\" width=\"1\" height=\"1\" border=\"0\" alt=\"WikiPeeks: ".$T." - Source: Wikipedia\"></span>$T</a>" . $bE . "</div>"; 
	}
	$countWiki++;
}
#-- WIKI END


?>