document.write('<object id="leFlasher" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="780" height="305" codebase="download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0">');
document.write('<param name="MOVIE" value="main.swf">');
document.write('<param name="wmode" value="transparent">');
document.write('<param name="PLAY" value="true">');
document.write('<param name="LOOP" value="false">');
document.write('<param name="QUALITY" value="high">');
document.write('<param name="MENU" value="false">');
document.write('<embed name="leFlasher" wmode="transparent" src="main.swf" width="780" height="305" play="true" loop="False" quality="high" menu="false" type="application/x-shockwave-flash" pluginspage="download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0">');
document.write('</embed>');
document.write('</object>');