<?php
##################################################################
#   Program:        OpenCanvas Interactive Website Design        #
#   Author:         Luis Gustavo Rodriguez (drlouie)             #
#   Copyright:      (c) 2009 Luis G. Rodriguez                   #
#   Licensing:      MIT License                                  #
#                                                                #
#   About                                                        #
#        Type:      User Interface Design and User Experience    #
#        Module:    Sidebar: OpenCanvas Website Categories       #
#        Do note:   PERL and PHP both reference this document.   #
#                   Perl uses include_php_vars() to do it.       #
##################################################################################
# Permission is hereby granted, free of charge, to any person obtaining a copy   #
# of this software and associated documentation files (the "Software"), to deal  #
# in the Software without restriction, including without limitation the rights   #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      #
# copies of the Software, and to permit persons to whom the Software is          #
# furnished to do so, subject to the following conditions:                       #
#                                                                                #
# The above copyright notice and this permission notice shall be included in all #
# copies or substantial portions of the Software.                                #
#                                                                                #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  #
# SOFTWARE.                                                                      #
##################################################################################

// replace zen-cart w zen cart in DB
// wikibooks for CRE Loaded and others

/// THIS PROGRAM ALSO RUNS THROUGH PERL WHICH MEANS WE CANNOT USE PERL SPECIAL CHARACTERS IN THE DATA, HENCE THE POUND SIGN [#]

$term = array("CMS", "Joomla", "osCommerce", "OS Commerce", "Adobe Flash", "Drupal", "PHP-Nuke", "PHPBB", "Zen Cart", "Zen-Cart", "XML Flash", "XML-Based", "Web 2.0", "SWISH MAX", "WordPress", "CSS Based", "CSS Skin", "After Effects", "Microsoft PowerPoint", "PSD", "Magento", "Mambo");
$desc = array(
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Content management system\\' title=\\'A content management system (CMS) is the collection of procedures used to manage work flow in a collaborative environment. These procedures can be manual or computer-based. The procedures are designed to do the following: Allow for a large number of people to contribute to and share stored data, control access to data, based on user roles (defining which information users or user groups can view, edit, publish, etc.), aid in easy storage and retrieval of data, reduce repetitive duplicate input, improve the ease of report writing and improve communication between users.\\'>CMS</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Joomla\\' title=\\'Joomla is a free and open source content management system (CMS) for publishing content on the World Wide Web and intranets and a modelviewcontroller (MVC) Web application framework that can also be used independently. Joomla is written in PHP, uses object-oriented programming (OOP) techniques and software design patterns[citation needed], stores data in a MySQL database, and includes features such as page caching, RSS feeds, printable versions of pages, news flashes, blogs, polls, search, and support for language internationalization.\\'>Joomla</a>", 
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=osCommerce\\' title=\\'osCommerce is a popular Open Source online shop e-commerce solution that is powered by a dedicated, strong, and ever growing community, and is released under the GNU General Public License.\\'>osCommerce</a>", 
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=osCommerce\\' title=\\'osCommerce is a popular Open Source online shop e-commerce solution that is powered by a dedicated, strong, and ever growing community, and is released under the GNU General Public License.\\'>osCommerce</a>", 
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Adobe Flash\\' title=\\'Adobe Flash Player is the standard for delivering high-impact, rich Web content. Designs, animation, and application user interfaces are deployed immediately across all browsers and platforms, attracting and engaging users with a rich Web experience.\\'>Adobe Flash</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Drupal\\' title=\\'Drupal is an open source content management platform powering millions of websites and applications. Its built, used, and supported by an active and diverse community of people around the world.\\'>Drupal</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=PHP-Nuke\\' title=\\'PHP-Nuke is a news automated system specially designed to be used in Intranets and Internet. The Administrator has total control of his web site, registered users, and he will have in the hand a powerful assembly of tools to maintain an active and 100% interactive web site using databases.\\'>PHP-Nuke</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=PhpBB\\' title=\\'phpBB is a free flat-forum bulletin board software solution that can be used to stay in touch with a group of people or can power your entire website. With an extensive database of user-created modifications and styles database containing hundreds of style and image packages to customise your board, you can create a very unique forum in minutes.\\'>PhpBB</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Zen Cart\\' title=\\'Zen Cart truly is the art of e-commerce; free, user-friendly, open source shopping cart software. The ecommerce web site design program is being developed by a group of like-minded shop owners, programmers, designers, and consultants that think ecommerce web design could be and should be done differently.\\'>Zen Cart</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Zen Cart\\' title=\\'Zen Cart truly is the art of e-commerce; free, user-friendly, open source shopping cart software. The ecommerce web site design program is being developed by a group of like-minded shop owners, programmers, designers, and consultants that think ecommerce web design could be and should be done differently.\\'>Zen Cart</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=XML\\' title=\\'The design goals of XML emphasize simplicity, generality, and usability over the Internet.\\'>XML</a> <a style=\\'cursor:pointer;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Adobe Flash\\' title=\\'Adobe Flash Player is the standard for delivering high-impact, rich Web content. Designs, animation, and application user interfaces are deployed immediately across all browsers and platforms, attracting and engaging users with a rich Web experience.\\'>Flash</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=XML\\' title=\\'The design goals of XML emphasize simplicity, generality, and usability over the Internet. The flexibility of the architecture behind an XML-Based website allows for easy content management by the most novice of technology users.\\'>XML-Based</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Web 2.0\\' title=\\'Web 2.0 websites include social networking sites, blogs, wikis, video sharing sites, hosted services, web applications, mashups and folksonomies. Web 2.0 is associated with web applications that facilitate participatory information sharing, interoperability, user-centered design, and collaboration on the World Wide Web. A Web 2.0 site allows users to interact and collaborate with each other in a social media dialogue as creators (prosumers) of user-generated content in a virtual community, in contrast to websites where users (consumers) are limited to the passive viewing of content that was created for them.\\'>Web 2.0</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=SWiSH Max\\' title=\\'SWiSH Max is generally considered to be a simpler and less costly Flash creation tool in comparison with Adobe Flash. SWiSH Max does not support some Adobe Flash features such as ActionScript 3.0, shape tweens, and bitmap drawing capabilities. It does, however, include general Flash creation features such as vector drawing, motion tweens, and symbol editing. In addition, SWiSH Max incorporates a number of automated effects and transitions, which make building certain Flash elements such as buttons, advanced transition effects, and interactive Flash sites simpler. One drawback of SWiSH Max is its inability to open or save .fla files, which limits exchanges between other programs to final .swf files.\\'>SWiSH Max</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=WordPress\\' title=\\'WordPress started in 2003 with a single bit of code to enhance the typography of everyday writing and with fewer users than you can count on your fingers and toes. Since then it has grown to be the largest self-hosted blogging tool in the world, used on millions of sites and seen by tens of millions of people every day.\\'>WordPress</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/w3c.htm?st=/TR/CSS21/\\' title=\\'CSS or Cascading Style Sheets have been used until now for text formatting but recently, developers have started using it for positioning and layouts. CSS layouts are still difficult and time-consuming to implement but their advantages are certainly worth the trouble. CSS-based website interfaces are widely supported by modern browsers but not by older browsers, allow extreme flexibility in positioning, increase usability by encouraging liquid design, keep the HTML/TEXT ratio at a low level thus decreasing load time and allow the display of main content first while the graphics load afterwards.\\'>CSS Based</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Cascading Style Sheets\\' title=\\'CSS or Cascading Style Sheets have been used until now for text formatting but recently, developers have started using it for positioning and layouts. CSS layouts are still difficult and time-consuming to implement but their advantages are certainly worth the trouble. CSS-skinned website interfaces allow extreme flexibility and ease for updating the look-and-feel of the website with minimal effort, increases usability by encouraging liquid design, keeps the HTML/TEXT ratio at a low level thus decreasing load time.\\'>CSS Skin</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Adobe After Effects\\' title=\\'Adobe After Effects is a digital motion graphics and compositing software published by Adobe Systems, used in film and video post-production. Its main uses are the origination of 2D and 2.5D animation, visual effects compositing and finishing (image adjustement, color correction etc.). After Effects can also be used as a basic non-linear editor and a media transcoder.\\'>After Effects</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Microsoft PowerPoint\\' title=\\'PowerPoint presentations consist of a number of individual pages or &lsquo;slides&rsquo;. The &lsquo;slide&rsquo; analogy is a reference to the slide projector. Slides may contain text, graphics, sound, movies, and other objects, which may be arranged freely. PowerPoint, however, facilitates the use of a consistent style in a presentation using a template or &lsquo;Slide Master&rsquo;. The presentation can be printed, displayed live on a computer, or navigated through at the command of the presenter. For larger audiences the computer display is often projected using a video projector. Slides can also form the basis of webcasts.\\'>Microsoft PowerPoint</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Adobe_Photoshop\\' title=\\'The .PSD (Photoshop Document), native image format for Adobe Photoshop, stores an image with support for most imaging options available in Photoshop. These include layers with masks, color spaces, ICC profiles, transparency, text, alpha channels and spot colors, clipping paths, and duotone settings. PSD mockups can be sliced up and easily turned into a functional website, presentation or application interfaces using the platform of your choosing.\\'>PSD</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Magento\\' title=\\'Magento eCommerce Platforms provide the scalability, flexibility and features for business growth. Magento provides feature-rich eCommerce platforms that offer merchants complete flexibility and control over the presentation, content, and functionality of their online channel.\\'>Magento</a>",
	"<a style=\\'cursor:pointer;display:inline;border:0px;\\' class=\\'MoreWikiInfo\\' onClick=\\'runWikiBoard(this);\\' rel=\\'/wikipedia.htm?st=Mambo (software)\\' title=\\'Mambo (formerly named Mambo Open Source or MOS) is a free software/open source content management system (CMS) for creating and managing websites through a simple web interface. Mambo includes advanced features such as page caching to improve performance on busy sites, advanced templating techniques, and a fairly robust API. It can provide RSS feeds and automate many tasks, including web indexing of static pages. Advanced interface features include printable versions of pages, news flashes, blogs, forums, polls, calendars, website searching, language internationalization, and many others.\\'>Mambo</a>"
);
?>
